config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  devise_for :users
  resource :user, except: [:new, :create, :destroy]
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	with_options presence: true do
		validates :title
		validates :body
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true
         has_many :books, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resouce)
		user_path
	end

	def after_sign_up_path_for(resouce)
		user_path
	end

	def after_sign_out_path_for(resouce_or_scope)
		new_user_session_path
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	@books = Book.all
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
  		redirect_to book_path(@book), notice: "投稿に成功しました！"
  	else
  		render :new
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  	unless @book.user_id == current_user.id
  		redirect_to books_path, alert: "不正なアクセスです！"
  	end
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to book_path(@book), notice: "投稿に成功しました！"
	else
		render :edit
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update(user_params)
			redirect_to user_path, notice: "ユーザー情報を更新しました！"
		else
			render :edit
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :profile, :profile_image, :profile_bg_image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

<div class="container mt-5">
	<div class="row">
		<div class="col-6 mx-auto">
			<h2>投稿編集</h2>
			<%= form_for @book do |f| %>
			<div class="form-group">
				<label>レシピ名</label>
				<%= f.text_field :title, class: "form-control" %>
			</div>

			<div class="form-group">
				<label>作り方</label>
				<%= f.text_area :body, class: "form-control" %>
			</div>

			<div>
				<%= f.submit "編集する", class: "btn btn-primary btn-block" %>
			</div>
			<% end %>

		</div>
	</div>
</div>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

<div class="container mt-5">
  <div class="row">
    <div class="col-10 mx-auto">
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">本のタイトル</th>
            <th scope="col">投稿者</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.user.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

<% if @book.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@book.errors.count, "error") %></h4>
    <p><%= pluralize(@book.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
	<div class="row">
		<div class="col-6 mx-auto">
			<h2>新規投稿</h2>
			<%= form_for @book do |f| %>
			<div class="form-group">
				<label>本のタイトル</label>
				<%= f.text_field :title, class: "form-control" %>
			</div>

			<div class="form-group">
				<label>本の概要</label>
				<%= f.text_area :body, class: "form-control" %>
			</div>

			<div>
				<%= f.submit "投稿する", class: "btn btn-primary btn-block" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>


<div class="container mt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= @book.title %></h5>
          <p class="card-text"><%= simple_format @book.body %></p>
          <p class="card-text">
            <small class="text-muted">更新日：<%= @book.updated_at.strftime("%Y-%m-%d") %></small>
          </p>
          <% if @book.user == current_user %>
            <%= link_to '編集', edit_book_path(@book), class: "btn btn-success" %>
            <%= link_to '削除', book_path(@book), method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'bookbook', root_path, class: "navbar-brand" %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "マイページ", user_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "新規投稿", new_book_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "投稿一覧", books_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>
      <% else %>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
      <% end %>
    </nav>

    <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(@user.errors.count, "error") %></h4>
    <p><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
    <hr>
    <p class="mb-0">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </p>
  </div>
<% end %>

<div class="container mt-5">
	<div class="row">
		<div class="col-6 mx-auto">
			<h2>ユーザー編集</h2>
			<%= form_for @user do |f| %>
			<div class="form-group">
				<label>ユーザー名</label>
				<%= f.text_field :name, class: "form-control" %>
			</div>

			<div class="form-group">
				<label>メールアドレス</label>
				<%= f.text_field :email, class: "form-control" %>
			</div>

			<div>
				<%= f.submit "更新する", class: "btn btn-primary btn-block" %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
	<div class="row">
		<div class="col-7 mx-auto">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title"><%= current_user.name %></h5>
					<h6 class="card-subtitle mb-2 text-nuted"><%= current_user.email %></h6>
					<%= link_to "ユーザー編集", edit_user_path %>
				</div>
			</div>
		</div>
	</div>
</div>